# Generated by Django 3.2.15 on 2023-01-02 11:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_dynamic'),
    ]

    operations = [
        migrations.AddField(
            model_name='dynamic',
            name='password',
            field=models.CharField(default=True, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dynamic',
            name='repassword',
            field=models.CharField(default=datetime.datetime(2023, 1, 2, 11, 50, 20, 804712, tzinfo=utc), max_length=254),
            preserve_default=False,
        ),
    ]
