# Generated by Django 4.1.4 on 2023-01-03 03:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_auto_20230102_1720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_name', models.CharField(max_length=100)),
                ('phone_model', models.CharField(max_length=100)),
            ],
        ),
    ]
