# Generated by Django 4.1.4 on 2023-01-03 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='price',
            field=models.FloatField(default=True),
            preserve_default=False,
        ),
    ]
