# Generated by Django 3.2.15 on 2023-01-07 02:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('app', '0019_cpu_proxystudent'),
    ]

    operations = [
        migrations.CreateModel(
            name='One2one',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('page_name', models.CharField(max_length=100)),
                ('page_cat', models.CharField(max_length=100)),
                ('page_publish_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('page', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.one2one')),
                ('likes', models.IntegerField()),
            ],
            bases=('app.one2one',),
        ),
    ]
