# Generated by Django 4.1.4 on 2023-01-07 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0024_many2manysong'),
    ]

    operations = [
        migrations.CreateModel(
            name='Crud_class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='many2manysong',
            name='song_duration',
            field=models.IntegerField(),
        ),
    ]
