# Generated by Django 3.2.15 on 2023-01-07 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_crud_class_alter_many2manysong_song_duration'),
    ]

    operations = [
        migrations.CreateModel(
            name='List',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('roll', models.IntegerField()),
                ('course', models.CharField(max_length=100)),
            ],
        ),
    ]
