# Generated by Django 3.2.15 on 2023-01-08 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0030_page'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='desc',
            field=models.TextField(max_length=250),
        ),
    ]
