# Generated by Django 4.1.5 on 2023-01-09 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0031_alter_page_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=100)),
                ('question_categories', models.CharField(max_length=100, verbose_name='how can we help you?')),
                ('message', models.TextField(max_length=300)),
            ],
        ),
    ]
